name: test_vulnerabilities
description: Trivy check for vulnerabilities
inputs:
  slack_token:
    description: 'Slack bot token'
    required: true
  ignore_found:
    description: Ignore found vulnerabilities
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Trivy check image for vulnerabilities
      shell: bash
      run: |
        ls -l
        trivy fs . --security-checks vuln --exit-code 1 --ignore-unfixed --severity "HIGH,CRITICAL" || result=$?
        if [[ "${{ inputs.ignore_found }}" == "true" ]]; then
          echo "Ignoring found vulnerabilities is set to true. Result is: $result"
          exit 0
        else
          echo "Test result is: $result"
          exit $result
        fi

    - uses: ./.github/actions/slack_notification
      if: failure()
      with:
        slack_token: ${{ inputs.slack_token }}
        message_pic: ':red_circle:'
        message: "Test vulnerabilities: Job failed for *${{ github.ref_name }}*!"
