apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tplchart.fullname" . }}
  labels:
    app: {{ template "tplchart.name" . }}
    chart: {{ template "tplchart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ template "tplchart.name" . }}
      chart: {{ template "tplchart.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app: {{ template "tplchart.name" . }}
        chart: {{ template "tplchart.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: {{ .Values.container.command | toYaml | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ template "tplchart.fullname" . }}-config
          env:
            {{- $secret_name := include "tplchart.fullname" . }}
            {{- range $name, $value := .Values.config.secret }}
            {{- if not ( empty $value) }}
            - name: {{ $name | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret_name }}
                  key: {{ $name | quote }}
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
