name: slack_notification
description: 'Sending notifications to slack'

inputs:
  mentions:
    description: 'Who to mention'
    required: false
    default: "" # @team
  message_pic:
    description: 'Pic in the beginning of text message'
    required: false
    default: ':white_check_mark:' #':red_circle:'
  message:
    description: 'Text message'
    required: true
  slack_token:
    description: 'Slack bot token'
    required: true

runs:
  using: composite
  steps:
    - name: Notify Slack channel
      id: slack_notify
      uses: slackapi/slack-github-action@v1.19.0
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack_token }}
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        channel-id: C02PK1L26N4
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "${{ inputs.message }} \n Actions url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n Commit url: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ inputs.message_pic }} ${{ inputs.message }}"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Job*: ${{ github.job }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Mentions*: ${{ inputs.mentions }}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Project*:\n ${{ github.repository }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Reference*:\n ${{ github.ref }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Commit*:\n ${{ github.sha }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Author*:\n ${{ github.actor }}"
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Job"
                    },
                    "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Notes"
                    },
                    "url": "${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
                  }
                ]
              }
            ]
          }
